using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
namespace TianGongCadSuite {
    public static class TrainingValidation {
        static object Get(Dictionary<string,object> d,string k){return TrainingDataset.Get(d,k);}
        static IEnumerable<Dictionary<string,object>> Rows(object x){return TrainingDataset.Rows(x);}
        static string[] Ids(object x){return x is IEnumerable?((IEnumerable)x).Cast<object>().OfType<string>().ToArray():new string[0];}
        static object Ratio(int a,int b){return b==0?null:(object)((double)a/b);}
        public static void Enrich(Dictionary<string,object> sample,Dictionary<string,object> summary){
            var errors=new List<string>();int meshed=0,faceCount=0,completeDims=0,refCount=0,boundRefs=0,asmRefs=0,mappedAsmRefs=0,datumRefs=0,datumBound=0,layoutDims=0;
            var models=Rows(Get(sample,"models")).ToArray();var allEdges=new HashSet<string>();var allFaces=new HashSet<string>();
            foreach(var model in models)foreach(var body in Rows(Get(model,"bodies"))){var faces=Rows(Get(body,"faces")).ToArray();var edges=Rows(Get(body,"edges")).ToArray();var fs=faces.ToDictionary(f=>(string)f["id"]);var es=edges.ToDictionary(e=>(string)e["id"]);allEdges.UnionWith(es.Keys);allFaces.UnionWith(fs.Keys);faceCount+=faces.Length;
                var topo=Get(body,"topology") as Dictionary<string,object>;var vs=new HashSet<string>(Rows(Get(topo,"vertices")).Select(v=>(string)v["id"]));
                foreach(var face in faces){string fid=(string)face["id"];if(Get(face,"edge_ids")==null)errors.Add(fid+":missing_edge_topology");foreach(string eid in Ids(Get(face,"edge_ids"))){Dictionary<string,object> e;if(!es.TryGetValue(eid,out e)||!Ids(Get(e,"adjacent_face_ids")).Contains(fid))errors.Add(fid+":asymmetric_face_edge");}foreach(string other in Ids(Get(face,"adjacent_face_ids"))){Dictionary<string,object> f;if(!fs.TryGetValue(other,out f)||!Ids(Get(f,"adjacent_face_ids")).Contains(fid)||!Ids(Get(face,"edge_ids")).Intersect(Ids(Get(f,"edge_ids"))).Any())errors.Add(fid+":invalid_adjacency");}}
                foreach(var edge in edges){string eid=(string)edge["id"];if(Get(edge,"vertex_ids")==null)errors.Add(eid+":missing_vertices");foreach(string vid in Ids(Get(edge,"vertex_ids")))if(!vs.Contains(vid))errors.Add(eid+":unresolved_vertex");foreach(string fid in Ids(Get(edge,"adjacent_face_ids"))){Dictionary<string,object> f;if(!fs.TryGetValue(fid,out f)||!Ids(Get(f,"edge_ids")).Contains(eid))errors.Add(eid+":asymmetric_edge_face");}}
                foreach(var loop in Rows(Get(topo,"loops"))){Dictionary<string,object> f;if(!fs.TryGetValue(Convert.ToString(Get(loop,"face_id")),out f)){errors.Add((string)body["id"]+":unresolved_loop_face");continue;}foreach(string eid in Ids(Get(loop,"edge_ids")))if(!Ids(Get(f,"edge_ids")).Contains(eid))errors.Add((string)loop["id"]+":invalid_loop_edge");}
                var mesh=Get(body,"mesh") as Dictionary<string,object>;var triangleFaces=Ids(Get(mesh,"triangle_face_ids"));if(mesh==null||triangleFaces.Length!=Convert.ToInt32(Get(mesh,"triangle_count")))errors.Add((string)body["id"]+":mesh_mapping_length");foreach(var fid in triangleFaces.Distinct())if(!fs.ContainsKey(fid))errors.Add((string)body["id"]+":foreign_triangle_face");meshed+=triangleFaces.Distinct().Count(fs.ContainsKey);
            }
            var modelKinds=models.ToDictionary(m=>(string)m["id"],m=>Convert.ToString(Get(m,"kind")));
            var working=Rows(Get(Get(sample,"drawing") as Dictionary<string,object>,"sheets")).Where(s=>Convert.ToString(Get(s,"section_type"))=="igWorkingSection").ToArray();
            var views=working.SelectMany(s=>Rows(Get(s,"views"))).ToDictionary(v=>(string)v["id"]);
            foreach(var view in views.Values){var section=Get(view,"section_data") as Dictionary<string,object>;foreach(var row in new[]{section}.Concat(Rows(Get(section,"cutting_planes"))).Concat(Rows(Get(section,"detail_envelopes"))).Concat(Rows(Get(section,"broken_out_profiles"))))if(row!=null)foreach(string field in new[]{"parent_view","child_view"})if(Get(row,field)!=null&&!views.ContainsKey(Convert.ToString(row[field])))errors.Add((string)view["id"]+":dangling_section_view");}
            foreach(var dim in working.SelectMany(s=>Rows(Get(s,"dimensions")))){var refs=Rows(Get(dim,"related_geometry")).ToArray();int matched=0;foreach(var related in refs){refCount++;var r=Get(related,"native_reference") as Dictionary<string,object>;var geom=Get(r,"native_geometry") as Dictionary<string,object>;bool valid=geom!=null&&allEdges.Contains(Convert.ToString(Get(geom,"id")));if(valid){matched++;boundRefs++;}else if(geom!=null)errors.Add((string)dim["id"]+":dangling_native_reference");Dictionary<string,object> view;string kind;if(views.TryGetValue(Convert.ToString(Get(r,"view_id")),out view)&&modelKinds.TryGetValue(Convert.ToString(Get(view,"model_id")),out kind)&&kind=="assembly"){asmRefs++;if(valid&&Ids(Get(r,"occurrence_path")).Length>0)mappedAsmRefs++;}}
                bool complete=refs.Length>0&&matched==refs.Length;if(complete)completeDims++;var layout=Get(dim,"layout") as Dictionary<string,object>;if(Get(layout,"text_position_sheet_m")!=null&&Ids(Get(dim,"view_ids")).Length>0)layoutDims++;
                dim["supervision"]=TrainingExporter.Obj("all_references_resolved",complete,"geometry_targets_available",complete&&(Get(dim,"value_m")!=null||Get(dim,"value_rad")!=null),"layout_targets_available",Get(layout,"text_position_sheet_m")!=null,"requires_review",true);
            }
            foreach(var datum in working.SelectMany(s=>Rows(Get(s,"annotations"))).Where(a=>Convert.ToString(Get(a,"kind"))=="datum")){datumRefs++;if(Rows(Get(datum,"references")).Any(r=>Get(Get(r,"native_reference") as Dictionary<string,object>,"native_geometry")!=null))datumBound++;}
            summary["topology_errors"]=errors.Count;summary["validation_errors"]=errors;summary["meshed_face_coverage"]=Ratio(meshed,faceCount);summary["dimension_all_native_references_coverage"]=Ratio(completeDims,Convert.ToInt32(summary["dimensions"]));summary["native_reference_count"]=refCount;summary["resolved_native_reference_count"]=boundRefs;summary["reference_native_geometry_coverage"]=Ratio(boundRefs,refCount);summary["dimensions_with_layout_and_view"]=layoutDims;summary["datum_native_reference_coverage"]=Ratio(datumBound,datumRefs);summary["occurrence_reference_count"]=asmRefs;summary["mapped_occurrence_reference_count"]=mappedAsmRefs;summary["occurrence_mapping_coverage"]=Ratio(mappedAsmRefs,asmRefs);
            summary["source_integrity_verified"]=Get(sample,"source_integrity_verified");summary["coverage_definition"]="dimension_native_reference_coverage: at least one valid native reference; dimension_all_native_references_coverage: every exported relation resolves; zero denominators are null";
            summary["feature_module_statuses"]=models.Where(m=>Get(m,"feature_tree")!=null).Select(m=>TrainingExporter.Obj("model_id",m["id"],"status",Get(Get(m,"feature_tree") as Dictionary<string,object>,"status"))).ToArray();
            summary["status"]=errors.Count>0?"failed":Convert.ToString(Get(sample,"extraction_status"))=="failed"?"failed":"success";summary["status_scope"]="structural validation only; module limitations and training_ready remain separate";
        }
    }
}
